### PR TITLE
Add retry

### PR DESCRIPTION
**Pull request by siavolt**
Add retry

### CODE REVIEW

**Comment by malko** [comment]
Thank's siavolt for your new contrib, i will have a look at it really soon, but i'm wondering if the retry shoudn't be more of an exponential backoff than an immediate retry. What do you thing about it ?

**Comment by siavolt** [comment]
Hi, Malko! We can add some arg for retry delay, something like that: { ..., maxTryCount: 3, delay: 400 }. and use setiTimeout, for default use 1000msec

**Comment by siavolt** [comment]
What are you think about that?

**Comment by malko** [comment]
I was more thinking of an automated [exponential backoff](http://en.wikipedia.org/wiki/Exponential_backoff). I make some comments to your pull request, i really think we must manage a delay before putting in a retry. Also i'm wondering (not really sure about that really) if it wouldn't be better to manage retry on a request basis instead of setting the retry logic for all request at once. What do you think about it?

**Comment by siavolt** [comment]
Done

**Comment by malko** [comment]
Hi i made some modification to your code.
Remove the requestParam and use a params.retry property if exists.
I still need to update the readme about the retry possibilities.
Can you please checkout the dev branch and review if this is ok for you in which case i'll try to make the doc and release a new version tonight.

thanks again for your contribution

**Pull request merged**
